config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'flights#index'
  resources :flights, only: %i[index]
  resources :bookings, only: %i[new show create]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: 'Flight', foreign_key: 'departure_airport_id', dependent: :destroy
  has_many :arriving_flights, class_name: 'Flight', foreign_key: 'arrival_airport_id', dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy
  accepts_nested_attributes_for :passengers, allow_destroy: true
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings, dependent: :destroy
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new

    @flight = Flight.find(params[:flight_id])
    
    @num_passengers = params[:num_passengers].to_i
    @num_passengers.times { @booking.passengers.build }
  end

  def create 
    @booking = Booking.new(booking_params)

    if @booking.save
      PassengerMailer.with(booking: @booking).confirm_email.deliver_later
      redirect_to @booking
    else
      render :new # status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @flight = @booking.flight
  end

  private 
  def booking_params
    params.require(:booking).permit(:flight_id, passengers_attributes: [:first_name, :last_name, :email, :_destroy])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
    @airport_options = Airport.all.map { |airport| [airport.code, airport.id] }
    @available_flights = find_flights
    
  end

  private

  def format_duration(duration)
    hrs = duration / 60
    min = duration % 60
    min = format('%02d',min)
    return "#{hrs}:#{min}"
  end

  def find_flights
    return [] unless params['depart_date(1i)'].present?

    @selected_date = Date.new(params['depart_date(1i)'].to_i, params['depart_date(2i)'].to_i, params['depart_date(3i)'].to_i)
    Flight.all.where(departure_airport_id: params[:departure_airport_id]).where(arrival_airport_id: params[:arrival_airport_id]).where("depart_date = ?", @selected_date)
  end

  def flights_params
    params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :depart_date, :flight_duration,
                                   :num_passengers, :depart_time)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/_flight_details.html.erb
    <h3 class="title is-5">Flight Details</h3>
    <div class="is-size-5"><%= "#{@flight.departure_airport.code} ⮕ #{@flight.arrival_airport.code}" %></div>
    <div><%= "Flight #: #{@flight.id}" %></div>
    <div><%= "Date: #{@flight.depart_date.strftime('%B %d, %Y')}" %></div>
    <div><%= "Time: #{@flight.depart_time.strftime('%-I:%M %p')}" %></div>
    <div><%= "Duration: #{@flight.flight_duration/60}h #{@flight.flight_duration%60}m" %></div>

app/views/bookings/new.html.erb
<br>
<div class="container">
  <section class="box">
    <h1 class="title is-4"> Your Trip Summary </h1>
    <div>
      <%= form_with model: @booking do |form| %>
        <div>
          <%= form.hidden_field :flight_id, value: params[:flight_id] %>
          <%= render 'flight_details' %>
        </div>
        <br>
        <h1 class="title is-5">Passenger Details</h1>
        <div>
          <% count = 1 %>
          <%= form.fields_for :passengers do |passenger_form| %>
            <div>
              <h1 class="has-text-weight-bold"><%= "Passenger #{count}:"%></h1>
              <div>
                <%= passenger_form.label :first_name, "First Name:" %>
                <%= passenger_form.text_field :first_name, required: true %>
                <%= passenger_form.label :last_name, "Last Name:" %>
                <%= passenger_form.text_field :last_name, required: true %>
                <%= passenger_form.label :email, "Email:" %>
                <%= passenger_form.text_field :email, required: true %>
              </div>
              <% count += 1 %><br>
            </div>
          <%end%><br>
          <%= form.submit "Finalize Booking", class: "button is-success" %>
        </div>
      <%end%>
    </div>
  </section>
</div>

app/views/bookings/show.html.erb
<br>
<div class="notification is-success is-light">
  Your flight is booked!
</div>

<div class="container">
  <section class="box">
<h1 class="title is-4"> Trip Summary </h1>

<%= render 'flight_details' %>
<br>
<h3 class="title is-5"> Passengers </h3>

<% @booking.passengers.each do |passenger| %>
  <div>
    <%= "#{passenger.first_name} #{passenger.last_name}" %>
  </div>
<% end %>

app/views/flights/_flights.html.erb
<h3 class="title is-4">AVAILABLE FLIGHTS</h3>
<%= form_with url: new_booking_path, method: :get do |form| %>
  <% if @available_flights.length == 0 %>
    <%= "No available flights on that date" %>
  <% else %>
    <%= form.hidden_field :num_passengers, value: params[:num_passengers] %>
    <% @available_flights.each do |flight| %>
      <table class="table is-narrow is-hoverable">
        <tr>
          <th><%= form.radio_button :flight_id, flight.id %></th>
          <th><%= flight.departure_airport.code %></th>
          <th>⮕</th>
          <th><%= flight.arrival_airport.code %> </th>
          <th><%= flight.depart_time.strftime('%-I:%M %p') %></th>
          <th><%= "Duration: #{flight.flight_duration/60}h #{flight.flight_duration%60}m" %></th>
        </tr>
      </table>
    <% end %>
    <%= form.submit "Book Flight", class: "button is-success"  %>
  <% end %>
<% end %>

app/views/flights/_search.html.erb
<%= form_with url: flights_path, method: :get do |form| %>
  <div class="field is-horizontal">
    <div class="field-body">
      <div class="field">
        <label class="label is-small"><%= form.label :departure_airport_id, "FROM" %></label>
        <div class="control">
          <div class="select is-primary"><%= form.select(:departure_airport_id, @airport_options, selected: params[:departure_airport_id]) %>
          </div>
        </div>
      </div>
      <div class="field">
        <label class="label is-small"><%= form.label :arrival_airport_id, "TO" %></label>
        <div class="control">
          <div class="select is-primary"><%= form.select(:arrival_airport_id, @airport_options, selected: params[:arrival_airport_id]) %>
          </div>
        </div>
      </div>
      <div class="field">
        <label class="label is-small"><%= form.label :num_passengers, "PASSENGERS" %></label>
        <div class="control">
          <div class="select is-primary"><%= form.select(:num_passengers, [1,2,3,4], selected: params[:num_passengers]) %>
          </div>
        </div>
      </div>
      <div class="field">
        <label class="label is-small"><%= form.label :depart_date, "DATE" %></label>
        <div class="control">
          <div class="select is-primary">
            <%= form.date_select :depart_date, start_year: Date.today.year, end_year: Date.today.year, use_short_month: true, order: [:month, :day, :year], selected: @selected_date, date_separator: '</div><div class="select is-primary">' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <br>
  <div class="field">
    <div class="control">
      <%= form.submit "Find Flights", class: "button is-success" %>
    </div>
  </div>
</div>
<% end %>

app/views/flights/index.html.erb
<br>
<div class="container">
  <section class="box">
    <div>
      <h1 class="title is-4">BOOK A ONE-WAY FLIGHT</h1>
      <h2 class="subtitle is-7">Find last minute flights for the next 30 days</h2>
      <%= render "search" %>
    </div>
  </section>
</div>
<br>
<% if params['depart_date(1i)'].present? %>
  <div class="container">
    <section class="box">
      <div>
        <%= render "flights" %>
      </div>
    </section>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar is-success" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to 'FLIGHTBOOKER ✈✈✈', root_path, class: "navbar-item is-size-3 has-text-weight-bold has-text-success-dark" %>
    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <%= link_to 'Find Last Minute Flights', flights_path, class: "navbar-item" %>
    </div>
    <div class="navbar-end">
      <div class="navbar-item">
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinRailsFlightTracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>